-- MySQL Script generated by MySQL Workbench
-- Mon Jan 18 07:46:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `proyecto` ;

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET utf8 ;
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `proyecto`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`clientes` (
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(90) NULL,
  `dni` VARCHAR(9) NOT NULL,
  `telefono` INT(10) NULL,
  `email` VARCHAR(100) NULL,
  `direccion` VARCHAR(150) NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`pedidos` (
  `codigo_PEDIDOS` INT(10) NOT NULL,
  `fecha_hora` DATETIME NULL,
  `dni_CLIENTES` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`codigo_PEDIDOS`),
  INDEX `fk_PEDIDOS_CLIENTES_idx` (`dni_CLIENTES` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDOS_CLIENTES`
    FOREIGN KEY (`dni_CLIENTES`)
    REFERENCES `proyecto`.`clientes` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`proveedores` (
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(90) NULL,
  `dni` VARCHAR(9) NOT NULL,
  `telefono` INT(10) NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`categorias` (
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`productos` (
  `codigo_PRODUCTOS` INT(10) NOT NULL,
  `marca` VARCHAR(50) NULL,
  `modelo` VARCHAR(75) NULL,
  `precio` DECIMAL(10,2) NULL,
  `caracteristicas` VARCHAR(1000) NULL,
  `dni_PROVEEDORES` VARCHAR(9) NOT NULL,
  `tipo` VARCHAR(25) NULL,
  `nombre_CATEGORIAS` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codigo_PRODUCTOS`),
  INDEX `fk_PRODUCTOS_PROVEEDORES1_idx` (`dni_PROVEEDORES` ASC) VISIBLE,
  INDEX `fk_PRODUCTOS_CATEGORÍAS1_idx` (`nombre_CATEGORIAS` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTOS_PROVEEDORES1`
    FOREIGN KEY (`dni_PROVEEDORES`)
    REFERENCES `proyecto`.`proveedores` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTOS_CATEGORÍAS1`
    FOREIGN KEY (`nombre_CATEGORIAS`)
    REFERENCES `proyecto`.`categorias` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`detalle_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`detalle_pedidos` (
  `codigo_PEDIDOS` INT(10) NOT NULL,
  `codigo_PRODUCTOS` INT(10) NOT NULL,
  `precioUnitario` VARCHAR(10) NULL,
  `cantidad` VARCHAR(10) NULL,
  PRIMARY KEY (`codigo_PEDIDOS`, `codigo_PRODUCTOS`),
  INDEX `fk_PEDIDOS_has_PRODUCTOS_PRODUCTOS1_idx` (`codigo_PRODUCTOS` ASC) VISIBLE,
  INDEX `fk_PEDIDOS_has_PRODUCTOS_PEDIDOS1_idx` (`codigo_PEDIDOS` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDOS_has_PRODUCTOS_PEDIDOS1`
    FOREIGN KEY (`codigo_PEDIDOS`)
    REFERENCES `proyecto`.`pedidos` (`codigo_PEDIDOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDOS_has_PRODUCTOS_PRODUCTOS1`
    FOREIGN KEY (`codigo_PRODUCTOS`)
    REFERENCES `proyecto`.`productos` (`codigo_PRODUCTOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
